### ISSUE TITLE
should `duffle uninstall` use the same creds the bundle was installed with? 

### ISSUE THREAD

**Issue by squillace** [deislabs/duffle#246]
This is an issue, not a request. I realize that hellohelm could have been installed with any number of cred sets. But each mapped instance {hellohelm, credset-1}, {hellohelm, credset-2} should duffle remember that combination and use the credset when uninstall is called, or is that optimization best left to VS Code?

My first reaction is VS Code, but I want to raise the issue.

duffle version `48dbf3c`

**Comment by jeremyrickard** [comment]
I don't think this would be a `duffle` thing, specifically because of the claim. VS Code, or some other tooling _could_ implement this in a mechanism beyond duffle however. Going to close this @squillace, let me know if we need to re-open it here to discuss.
