### ISSUE TITLE
Clarify the workings of 'base bundles'

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#290]
We refer informally to 'base bundles' such as `library/terraform`, `library/makebase`, `library/armbase` etc.  These include base invocation images that an actual Terraform or ARM app bundle could layer on top of to bootstrap all the boring bits of _its_ invocation image.  For example, they might provide an `app/run` which calls a tool passing a template which is not on the base image but is intended to be placed in the image by the layered bundle.

There are a few things with the use of base bundles which are not clear:

* How do they compose?  If I am creating a bundle where I am using both Terraform and ARM, can I compose the two base images, or do I pick one to start with and then copy-paste source code from the other?
* They may define parameters in their `bundle.json`.  The layered bundle may need to surface these parameters.  Or it may want to set some of them to fixed values (to nail down the behaviour).  Or it may want to set some of them to generated values based on a simpler value supplied by the user of the layered bundle.  How is this done?  Does the user copy the `bundle.json` in the base bundle and then modify and extend it as required (so that the base bundle.json is no longer referenced in the final bundle, only the base images are).
* Similarly with credentials.

We can address the `bundle.json` issue through documentation and tooling (e.g. a developer guide, a 'generate bundle from base bundle' command that creates a starter invocation image Dockerfile and copied `bundle.json`, etc.).  It doesn't feel like a great ecosystem but it avoids any need for protocols for chaining bundles together, and avoids shipping a hurried solution that then becomes a compatibiity constraint.  Not sure if the compose issue has any better story than "they're open source, go stitch them together yourself" though...?

**Comment by jeremyrickard** [comment]
We've de-emphasized the concept of base bundles, so I'm going to close this.
