### ISSUE TITLE
Build then credentials generate fails with repo error

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#358]
With the #307 local bundle store, if I do a `duffle build` then immediately do a `duffle credentials generate` on the resulting bundle, it fails with `Error: request to https://hub.cnlabs.io/repositories/htest/tags/608a64da8e1c7430cab7e03be4ceecf6a9ae8331 responded with a non-200 status code: 404` - it is trying to hit the remote repo rather than the local store, even though the local bundle has no repo prefix.

Presumably related to #317.

**Comment by radu-matei** [comment]
#384 should close this.

Feel free to re-open if the issue still persists.
