### ISSUE TITLE
`make bootstrap` fails on Windows

### ISSUE THREAD

**Issue by radu-matei** [deislabs/duffle#365]
The `bootstrap` target is the only one failing on Windows - `curl` might (or might not) be present, but piping to `sh` will surely fail:

```
.PHONY: bootstrap
bootstrap:
ifndef HAS_DEP
	curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
endif
ifndef HAS_GOLANGCI
	curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(GOPATH)/bin
endif
```
(Related: #271, #303)

**Comment by jeremyrickard** [comment]
We've since updated the build process and this is no longer needed (containerzed build process and no bootstrap target).
