### ISSUE TITLE
Bug: Use root command writer instead of `fmt.Print`

### ISSUE THREAD

**Issue by radu-matei** [deislabs/duffle#370]
There are a [bunch of places where the provided writer is not used](https://github.com/deis/duffle/search?q=fmt.printf&unscoped_q=fmt.printf).

In order to keep everything consistent, we should change them to use it.

**Comment by youreddy** [comment]
Going to take this issue and submit a PR for it.

/cc @ryanmoran

**Comment by youreddy** [comment]
Hey @radu-matei, we created [PR#626](https://github.com/deislabs/duffle/pull/626) to address the issue. As far as we could tell, the Warning methods don't get used anywhere and there weren't any tests to validate the Ohai logging package. We ended up just compiling the binary with our changes. Let us know if we missed something!

**Comment by radu-matei** [comment]
Closed in #626.

Thanks a lot for your contribution!
