### ISSUE TITLE
`duffle build` appears to discard parameter types

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#453]
I have the following in `duffle.toml`:

```
[parameters]
    [parameters.port]
        type = "int"
        defaultValue = 9999
        minValue = 2048
        maxValue = 32768
```

When I run `duffle build` I get this output:

```
  "parameters": {
    "port": {
      "type": "",
      "defaultValue": 9999,
      "required": false,
      "minValue": 2048,
      "maxValue": 32768,
      "metadata": {},
      "destination": null
    }
  },
```

The `type` attribute appears to have been discarded, which makes the generated JSON illegal according to the schema, and prevents confident validation.

**Comment by jeremyrickard** [comment]
There have been a number of changes to the build workflow, notably `duffle.toml` is no more, and the parameter structure / definitions have changed dramatically. In that time, this seems to be over come by events, so I'm closing it.
