### ISSUE TITLE
`duffle export` creates artifacts directory, and includes it in subsequent exports

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#456]
Create a bundle that references an image, e.g. `nginx`.

Do a `duffle export -u` of that bundle.  This creates an artifacts directory containing `nginx.tar`.

Now do a `duffle export -u=false`.  This is meant to create a thin bundle.  But because the artifacts directory from the previous export is still around, the artifacts including the very large tar file get dragged in anyway.

**Comment by michelleN** [comment]
With the updated directory structure and export changes in #578, this should no longer be a concern. You'll never have an artifacts directory created in the current working directory or source. It will only be created in the export artifact.

**Comment by michelleN** [comment]
resolved with #578
