### ISSUE TITLE
`duffle export` thin bundle syntax is non-obvious

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#457]
`duffle export` provides the `-u` switch to create a thick bundle.  However, `duffle export` implicitly sets `-u`.  To create a thin bundle, you need to write `-u=false`.  This is not clear from the documentation.  Even after I realised `-u` was on by default, I was trying things like `-u false` and getting nowhere.

I feel it would be clearer if the presence of the switch (without a value) _changed_ the behaviour, rather than leaving it the same.  If we feel thick exports should be the default, then I'd suggest having a 'thin' switch e.g. `--manifest-only`, rather than requiring people to know the Cobra convention.

**Comment by michelleN** [comment]
resolved with #578
