### ISSUE TITLE
`duffle export` does not appear to handle signed bundles (and error is misleading)

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#500]
(with a `data` directory containing a `bundle.cnab`)

```
> duffle export .\data -o .\data\bundle.tgz
Error: Error loading bundle: cannot download bundle file: Get c:\GitHub\duffle-bag\data\bundle.json: unsupported protocol scheme "c"
```

True, I don't have a `bundle.json` but I do have a `bundle.cnab`; should it not export that instead?

(I can't specify `.\data\bundle.cnab` because `duffle export` always appends `bundle.json` to the path so only works on directories.  If I try, it complains about `.\data\bundle.cnab\bundle.json` instead.)

Also, the error is misleading; it is nothing to do with protocol schemes, it's that it's looking for a file that doesn't exist.

**Comment by michelleN** [comment]
resolved with #578
