### ISSUE TITLE
add actions to `duffle build`

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/duffle#552]
Similar to parameters and credentials, we need to be able to add actions to a bundle through `duffle build`.

See https://github.com/deislabs/bundles/pull/26 for an example bundle that utilizes actions.

**Comment by ryanmoran** [comment]
Is this not resolved by https://github.com/deislabs/duffle/pull/567?

**Comment by radu-matei** [comment]
Yes, you are correct, thanks for catching this.

Closing.
