### ISSUE TITLE
Export from file system should take a file not a directory

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#582]
At the moment 'duffle export foo' treats foo as a directory, and looks for a bundle.json or bundle.cnab according to whether the '--insecure' flag is passed.  For consistency with othe commands, I suggest:

* export foo: exports from local store (and supports version)
* export -f path: exports from filesystem and treats path as a file name not a directory and infers signedness from file format
* --insecure flag skips signature verification for signed bundles, does nothing on unsigned bundles

Thoughts?  cc @michelleN

**Comment by michelleN** [comment]
+1 to all of this

**Comment by michelleN** [comment]
Having a required arg or flag is a bit confusing. We decided to be able to take an arg that is either a bundle reference or a path to a signed or unsigned bundle file as the arg. The `-f` is no longer needed in this scenario and duffle is responsible for figuring out whether the given arg is a file path or a bundle reference.

**Comment by itowlson** [comment]
In that case you _must_ provide a way to override Duffle's strategy.  Consider:

* Local store contains bundle `foo`
* Current directory contains file `foo`

What does `duffle export foo` do?  Let's say it chooses the bundle reference.  But in an IDE scenario the user could right-click the file `foo` and issue the export command.  How can I tell Duffle to export the `foo` _file_ instead of the bundle reference?

Possible strategy:

* Positional parameter for the bundle/file name as you suggest.
* By default, pick whichever one exists.
* If both exist, by default prompt or error.
* Allow a flag to control how the name is interpreted e.g. `duffle export foo --source=file` vs `duffle export foo --source=bundle`.
* If the flag is present, then do not check for the other source.  E.g. if source is `file` and the file doesn't exist but the bundle does, then error instead of using the bundle.  Never prompt if the flag is present.

"Pick whichever exists" as a default still feels slightly dangerous because users forget what context they're in ("aargh no I didn't mean THAT `foo`"), but bundle references and file names will usually be distinct enough that this shouldn't be an issue for us.

**Comment by michelleN** [comment]
At the moment, it checks if the name passed in is pathy (does is contain`/`) and if not, then find bundle in local store.
- I really like your idea of adding the source flag and will add that to the PR
- I was under the impression before that you had to export a bundle that follows the convention `name:version` and that is not currently the case. I think if you're trying to export a bundle from the local store then we should require the user to provide the bundle name and version. That way if we are in the case that we have a bundle called `foo` and a directory called `foo`, then a user cannot expect that the bundle from local store will be exported bc it they are not using a valid bundle reference. If we like this idea, then I can also change the algorithm to first identify whether the bundle reference looks like a bundle. I'll also need to update the current algorithm to do more than just check if the arg looks pathy and actually go and see if foo is a `directory` in the current directory.

What do you think @itowlson ?

**Comment by itowlson** [comment]
I'm not sure about requiring a version - think that one needs to be raised to the team/community for discussion.  But I don't think requiring one helps you distinguish - isn't the colon a legal filename character on Unix, i.e. you can have a file called `foo:bar`?  (Even on Windows, `c:foo` could mean "bundle `c` version `foo`" or "file `foo` in the current directory on drive `c`... though both of those would be pretty weird!)

I am doubtful about using / as an "it's a file" indicator - won't bundles have scopes like `itowlson/helloworld:0.0.1`?  Again could be wrong here.

My feeling is if we have a source flag then what we should do is:

* If the source flag is present, respect that.
* If the source flag is NOT present, check BOTH file and store.
  * If only one exists, use that.
  * If both exist, prompt (or fail).

If we try to guess which it is based on the 'look' of the name, then can become one more thing users have to understand to avoid surprises.  I suspect collisions will be rare enough that a naive 'check both' strategy will work just as well as a clever algorithm anyway.

Except... except if the bundle is named `a:something` and you're on Windows... urgh...

**Comment by michelleN** [comment]
I hear ya. I'd like to avoid prompting the user if we can here. The less human interaction, the better to get to the end result, the better.
How about we just make the default behavior checking the local bundle store? If you want to pass in a path instead then just use the `--source-is-file` flag or some flag with a better name?

**Comment by itowlson** [comment]
I like the complete unambiguousness of that.  It's like the `-f` flag but without the confusing "you need a positional argument if X but the option argument if Y".  :shipit:

**Comment by carolynvs** [comment]
I don't see the usability problem with `duffle export -f bundle.json`. It is similar to for example `kubectl apply -f doughnuts.yaml`. 

It's unambiguious and people are used to it from other CLIs. I like that the flag is explicit and doesn't require contextual explaining, "Sometimes the positional argument mean this, except when this flag is set, then it means this". The logic spelled out in the above comemnts is (to me) more confusing than using a flag, no?

**Comment by itowlson** [comment]
@carolynvs But I feel there's a difference in that `kubectl apply` doesn't have an alternative semantics for names.  If we go with `duffle export -f bundle.json` then I feel the alternative (referring to the local store) should be e.g. `duffle export -b itowlson/helloworld`, _not_ `duffle export itowlson/helloworld`.  I.e. if we are going to pass the bundle under a flag then arguably we should _always_ use a flag rather than sometimes use a flag and sometimes a positional argument.  To be honest that ends up pretty similar to `duffle export foo --source=file` vs `duffle export foo --source=bundle` but I see your point that it's clearer to have the 'what it means' be right there on the name argument rather than on a separate flag.

I'd be perfectly happy with a `-f/-b` where you _must_ pass one or the other.

**Comment by michelleN** [comment]
If we can follow the mantra `args are required and flags are optional`, then using a flag for every instance of this command would not be ideal.

I also don't think we should follow `kubectl` as a canonical example cli UX. Let's take a look at more common package management examples like `brew`, `helm`, `apt` and the `comparison of commands` section in [this wiki](Comparison of commands) as examples to follow.
