### ISSUE TITLE
Duffle init does not create a verification key

### ISSUE THREAD

**Issue by isurulucky** [deislabs/duffle#607]
As per the bundle signing guide [1], a verification key should be created along with a signing key when duffle is run for the first time. But `duffle key list` shows only one:

NAME                        TYPE   	FINGERPRINT                                    
xxx <xxx@yyy>	   signing	        87E1 1A8 E1E2 78YT C163 AE45 B62F 7A31 670 119P

duffle version is 0.1.0-ralpha.4+dramallamabuie-35-g2af5fe4.

[1]. https://github.com/deislabs/duffle/blob/master/docs/guides/signing-guide.md

**Comment by technosophos** [comment]
A signing key is automatically a verification key. I'll have to read through that guide to see if there is some terminology we can clean up.
