### ISSUE TITLE
[bug] duffle bundle sign fails 

### ISSUE THREAD

**Issue by isurulucky** [deislabs/duffle#608]
`$ duffle bundle sign myfirstbundle:0.1.0 -o bundle.cnab`
gives the output: 
**Error: invalid character '-' in numeric literal**

duffle version is 0.1.0-ralpha.4+dramallamabuie-35-g2af5fe4.

**Comment by radu-matei** [comment]
This seems to be the same issue as #540.
Closing, as #540 has a bit more context -- feel free to re-open if you think it's not the same issue.

Thanks!
