### ISSUE TITLE
Exporting the helloworld example.

### ISSUE THREAD

**Issue by jayunit100** [deislabs/duffle#610]
The first thing I tried to do with duffle was export the helloworld example.  The reason I tried this is its one of the main value-add of CNAB over pure deployers like helm. 

So, here's what I ran into.. Mostly confusion around bundle.json vs. duffle.json (see #609 #330 #329  for related issues.  This might be simply another version of #609.

I can build the example.  I tried manually making a bundle.json so I could export it but there was a complaint that the .cnab file didnt exist. 

Is there any documentation on how to build a .cnab file from a duffle.json, so that I can try exporting it?

```
➜  helloworld git:(master) ✗ duffle build ./
Step 1/6 : FROM alpine:latest
 ---> 3f53bb00af94
Step 2/6 : RUN apk update
 ---> Using cache
 ---> e808ff8b34a5
Step 3/6 : RUN apk add -u bash
 ---> Using cache
 ---> ef757e4463ff
Step 4/6 : COPY Dockerfile /cnab/Dockerfile
 ---> Using cache
 ---> 61707a2ae06a
Step 5/6 : COPY app /cnab/app
 ---> Using cache
 ---> ab748f5a1ef6
Step 6/6 : CMD ["/cnab/app/run"]
 ---> Using cache
 ---> a99051f28e6e
Successfully built a99051f28e6e
Successfully tagged deislabs/helloworld-cnab:43d45307a7e09da6d216da5cfce2a49d9af864fc
==> Successfully built bundle helloworld:0.1.0
➜  helloworld git:(master) ✗ ls
bundle.json cnab        duffle.json
➜  helloworld git:(master) ✗ duffle export ./
Error: Bundle manifest not found at /Users/jayunit100/go/src/github.com/deislabs/duffle/examples/helloworld/bundle.cnab
➜  helloworld git:(master) ✗ cat bundle.json

{
    "name": "helloworld",
    "version": "0.1.0",
    "invocationImages": {
        "cnab": {
            "name": "cnab",
            "builder": "docker",
            "configuration": {
                "registry": "deislabs"
            }
        }
    }
}
```

**Comment by bacongobbler** [comment]
Because the helloworld example uses an unsigned bundle, you'll need to pass the `--insecure` flag to `duffle export`. Does that work?

**Comment by bacongobbler** [comment]
alternatively, you can call `duffle bundle sign -o bundle.cnab` before calling `duffle export` to sign the bundle using your PGP key that was generated for you (see `duffle key list`).

**Comment by jayunit100** [comment]
in general , there is no bundle.json , i just made one up.

Should there be one in this repository?   I guess I'm confused about where duffle.json ends and bundle.json begins :).

**Comment by jayunit100** [comment]
--insecure seems to get me further, but i think my hacked up bundle.json is incorrect... not sure wether i shoudl fix it , or wether we should just have a bundle.json in this repo for `helloworld`.
```
duffle export --insecure ./
Error: Error loading bundle: json: cannot unmarshal object into Go struct field Bundle.invocationImages of type []bundle.InvocationImage
```

**Comment by bacongobbler** [comment]
Yeah, that error seems to indicate a malformed duffle.json. would you mind posting it here so we can see what's wrong?

**Comment by chris-crone** [comment]
@jayunit100 Looking at your `bundle.json`, it's invalid as _invocationImages_ is a map instead of a list.

You can try with something like this:
```json
{
  "name": "helloworld",
  "version": "0.1.1",
  "description": "A short description of your bundle",
  "keywords": [
    "helloworld",
    "cnab",
    "tutorial"
  ],
  "maintainers": [
    {
      "name": "Jane Doe",
      "email": "jane.doe@example.com",
      "url": "https://example.com"
    }
  ],
  "invocationImages": [
    {
      "imageType": "docker",
      "image": "cnab/helloworld:0.1.1"
    }
  ],
  "images": null,
  "parameters": null,
  "credentials": null
}
```

I used the above `bundle.json` for an example of our [CNAB to OCI repo](https://github.com/docker/cnab-to-oci).

**Comment by jayunit100** [comment]
Cool ! It worked! .  Can someone  just PR that particular file into this repo , so that the example standsalone ... or is there a way to generate it ? 

Since, bundle.json is required if you want to export an app, so I'd say its really a core requirement for any example CNAB app... Unless it can be generated automatically via duffle.

Somewhat puzzled though, because I got a new error w/ a different bundle.json: 

```
➜  helloworld git:(master) ✗ duffle export --insecure ./
Error: Bundle manifest not found at /Users/jayunit100/go/src/github.com/deislabs/duffle/examples/helloworld/bundle.json
```

However, when I rewrote the bundle.json to match whats above, it fixed it !
```
➜  helloworld git:(master) ✗ mv bundle2.json bundle.json
➜  helloworld git:(master) ✗ duffle export --insecure ./
➜  helloworld git:(master) ✗ ls
bundle.json          cnab                 duffle.json          helloworld-0.1.1.tgz
```

Great news is that the export works find for helloworld, for me, so I can begin building off of this.
