### ISSUE TITLE
duffle push does not push completely to dockerhub.

### ISSUE THREAD

**Issue by madajaju** [deislabs/duffle#611]
I build a bundle test it out then try to push it to my dockerhub. It creates the repository but there are not images in the repository.
duffle.json looks like this.

name: ingestion
version: 0.1.3
description: Ingestion application
keywords: []
maintainers: []
components:
  cnab:
    name: cnab
    builder: docker
    configuration:
      registry: madajaju
parameters:
  context:
    type: string
    defaultValue: local
credentials: []

build creates the image madajaju/ingestion-cnab:...
Bundle that gets created is docker.io/library/ingestion:0.1.3

When I try to push it will not work because I don't have permission to write to the top of dockerhub.

I made a change to the duffle.yml to prepend madajaju/ to the name.

name: madajaju/ingestion
version: 0.1.3
description: Ingestion application
keywords: []
maintainers: []
components:
  cnab:
    name: cnab
    builder: docker
    configuration:
      registry: madajaju
parameters:
  context:
    type: string
    defaultValue: local
credentials: []

Now it creates a image madajaju/madajaju/ingestion-cnab:...
And the bundle docker.io/madajaju/ingestion:0.1.3

Now when I push madajaju/ingestion:0.1.3 it creates the repository in dockerhub, but does not put the invocation image in there. Probably because the name is madajaju/madajaju/ingestion.

do you have a work around? What am I doing wrong.

**Comment by radu-matei** [comment]
Hi, and thanks for opening the issue!

Working with a registry is not fully implemented at this point, as we are working towards standardizing this within the Open Container Initiative. (You can find the discussions on the OCI mailing list, [here](https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/qYM84b0vays) and [here](https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/U49AZRFo3tk)).

However, if you want to distribute the invocation image alone, you can directly use the Docker CLI for now.
Let us know if you have any questions.

Thanks!

**Comment by madajaju** [comment]
Thanks.
