### ISSUE TITLE
`duffle upgrade` documentation and implementation mismatch

### ISSUE THREAD

**Issue by ystros** [deislabs/duffle#621]
Currently, the `--help` command for `duffle upgrade` says that you can specify a new bundle for an installation as the second parameter:

```
  duffle upgrade NAME [BUNDLE] [flags]
```

However, in the implementation for the upgrade command, an error is immediately thrown unless the command received **exactly** one argument:
https://github.com/deislabs/duffle/blob/020331d9b3fff375b5acc87ce9467ca15011aeed/cmd/duffle/upgrade.go#L52

As such, there doesn't seem to be a way to specify the upgraded bundle name/version to the command.

**Comment by madamkiwi** [comment]
This issue seems to have been addressed with the latest code.  The bundle is now a flag.
