### ISSUE TITLE
duffle bundle remove not working 

### ISSUE THREAD

**Issue by michelleN** [deislabs/duffle#692]
Errors every time.

**Comment by michelleN** [comment]
I thought it wasn't working but it turns out it was just not working how I expected. I expected to be able to be able to remove a bundle like this `duffle bundle rm helloworld:0.1.0` but the correct syntax is `duffle bundle rm helloworld -r 0.1.0` which works just fine.

**Comment by radu-matei** [comment]
Implemented in #852
