### ISSUE TITLE
Refresh the protected branches rules

### ISSUE THREAD

**Issue by radu-matei** [deislabs/duffle#701]
We need to update the protected branches such as:

- no one should be able to push directly to `master`
- all PRs must have all checks passing before merging into `master`

Any thoughts on this?

**Comment by radu-matei** [comment]
So I'm looking at the protection rules, and I think we can enable:

- require PRs before merging
- require status checks
- include administrators

<img width="822" alt="Screen Shot 2019-04-06 at 19 14 46" src="https://user-images.githubusercontent.com/13103165/55672154-4c528980-58a0-11e9-8cfd-34db5129ef6a.png">

Thoughts?

**Comment by michelleN** [comment]
@radu-matei those all sound good to me 👍

**Comment by radu-matei** [comment]
One benefit of this is the fact that we will no longer be able to merge branches that are out of date with the master branch, even if there are no conflicts (which is exactly the issue that hit me during the weekend).

**Comment by radu-matei** [comment]
Updated the branch rules for `master`, as shown below. Closing this, but also opened #710 to track adding a `CODEOWNERS` file to automatically require reviews from code owners.
Thanks!

<img width="573" alt="Screen Shot 2019-04-11 at 17 07 53" src="https://user-images.githubusercontent.com/13103165/55963946-644d5300-5c7c-11e9-8791-f031d46ac872.png">
