### ISSUE TITLE
`duffle export` assumes current directory is writeable

### ISSUE THREAD

**Issue by glyn** [deislabs/duffle#721]
It seems that `duffle export` uses the current directory as a scratch area. Probably better to use a temporary directory.

## Steps to reproduce
1. cd to a read-only directory such as `/` on *ix
2. issue an export command such as:
```
duffle export $GOPATH/src/github.com/deislabs/duffle/cmd/duffle/testdata/relocate/bundle.json -f -o /tmp/export.tgz
```
3. Observe an error like this:
```
Error: mkdir /testrelocate-0.1-export: permission denied
```

**Comment by michelleN** [comment]
yea it's definitely better to use temp directory as a scratch area rather than current directory. 👍

**Comment by glyn** [comment]
Note that @benpatt is working on a fix.
