### ISSUE TITLE
something is up with duffle CI

### ISSUE THREAD

**Issue by michelleN** [deislabs/duffle#729]
Something is hanging with the duffle ci setup. I can't tell if the CI check is failing in brigade or in azure devops. I think the problem is with the brigade set up. @vdice can you confirm?

**Comment by vdice** [comment]
It looks like the Azure Pipelines GitHub App just needed to be (re?)-installed into this project.  It's installed now and appears to be updating PRs properly, so we should be good...

**Comment by michelleN** [comment]
thank you! will close out now.
