### ISSUE TITLE
duffle-CI is inactive

### ISSUE THREAD

**Issue by glyn** [deislabs/duffle#737]
duffle-CI doesn't seem to want to run:
![Screenshot 2019-04-30 at 09 10 11](https://user-images.githubusercontent.com/94953/56952583-8a0aa100-6b32-11e9-8ac6-0abea42189fc.png)

It should either be fixed or the check should be removed in which case we make do with deislabs-ci.

**Comment by glyn** [comment]
https://github.com/deislabs/duffle/pull/736 reproduces this issue

**Comment by radu-matei** [comment]
Yeah, a couple of weeks ago we renamed the organization in Azure Pipelines to match the GitHub one (deislabs), and in the process, the build webhook changed.

We fixed that, and thought everything went back to normal...

**Comment by radu-matei** [comment]
This is weired - apparently, all build pipelines we used to have are gone:

![image](https://user-images.githubusercontent.com/13103165/56955356-cbf31180-6b49-11e9-8ef9-ca92aeb8af59.png)

**Comment by vdice** [comment]
Oops, missed this while away.  The `duffle-CI` Azure Pipelines hook had been removed after realizing all of its functionality was duplicated by our Brigade pipeline (which remains).  It will be easy to add back if/when we have tasks that we want Azure Pipelines to run apart from Brigade...

**Comment by radu-matei** [comment]
The main reason I think it makes sense to also have Azure Pipelines CI is to add builds for actual Windows and macOS environments.

**Comment by carolynvs** [comment]
I have removed Duffle-CI from the required checks so that it doesn't prevent PRs from being marked as ready to merge. I'm going to close this now since I believe that resolves the original concern (stuff was messed up and confusing).
