### ISSUE TITLE
duffle build bug

### ISSUE THREAD

**Issue by michelleN** [deislabs/duffle#738]
```
"invocationImages": {
        "directory-name": {
            "name": "image-name",
            "builder": "docker",
            "configuration": {
                "registry": "chzbrgr71"
            }
        }
    }
```
when `directory-name` is different from `image-name`, you'll get an error like: ````Error: cannot prepare build: could not find an invocation image for image-name``` bc it is not looking for the directory name correctly. 

discovered by Brian Redmond and Joey Schluchter. Thanks!

**Comment by glyn** [comment]
Since this bug was raised,`invocationImages` changed to be an array, so I think the bug is no longer reproducible. Please re-open if there is still a bug.
