### ISSUE TITLE
Turn off automatic review requests

### ISSUE THREAD

**Issue by glyn** [deislabs/duffle#745]
Currently a bot automatically requests a review from all the core maintainers.

I’m not keen on a bot doing this as, with a large set of maintainers, it clouds what’s really required.

In other projects, maintainers subscribe to the repo and keep an eye on PRs.

Similarly, raisers of PRs should be free to nominate particular reviewers (oh except they can’t because I don’t think we have any automation like prow to allow them to do that, but at least they can add a comment `/cc @somemaintainer`).

**Comment by silvin-lubecki** [comment]
Could we also prevent merging a PR onto master without at least 2 approvals?

**Comment by glyn** [comment]
Yes: 
![Screenshot 2019-05-10 at 15 26 47](https://user-images.githubusercontent.com/94953/57534517-176ea200-7338-11e9-9965-03ac07c6def6.png)

**Comment by carolynvs** [comment]
I'm not clear if duffle needs 1 or 2 reviewers? I know cnab-spec needs 2.

**Comment by glyn** [comment]
> I'm not clear if duffle needs 1 or 2 reviewers? I know cnab-spec needs 2.

That was my recollection for cnab-spec, but it's not currently enforced.

**Comment by carolynvs** [comment]
I just went rogue and turned on enforcing the CLA bot, and the validation test and requiring 2 reviews on cnab-spec. I don't feel comfortable changing the duffle settings since we don't have clear recollection/agreement on the rules to enforce though.

**Comment by carolynvs** [comment]
Also I too would really like the bot turned off and instead have people be able to assign reviewers via a comment like prow. When everyone is assigned, no one feels responsible, and it's hard to track which PRs you really cared about reviewing.

**Comment by technosophos** [comment]
Yeah, we need to require two approvals per PR, as @silvin-lubecki suggests.

**Comment by carolynvs** [comment]
I have fixed our GH settings to require 2 reviews just like cnab-spec.

**Comment by silvin-lubecki** [comment]
Should we close the issue then ? Or is the bot asking for reviewers still up?

**Comment by carolynvs** [comment]
I didn't change the bot because I have no clue where it's configured. 😀 So yeah we need to leave this open. Maybe @radu-matei knows?

**Comment by technosophos** [comment]
The "bot" is actually just the way that CODEOWNERS works. Anyone on the `*` line will be added to the Reviewers list, since in GitHub's opinion, this is what a global owner does.

Consequently, if you _don't_ want to get pinged for every PR, change your CODEOWNERS entry to not be on the `*` line.

**Comment by glyn** [comment]
I don't think this issue will really be addressed unless all the owners are moved off the `*` line. If one or two of us do this, then we'll probably miss out as PR raisers will see a bunch of reviewers added automatically and probably not think to add others.

**Comment by technosophos** [comment]
Did you have an alternative in mind?

**Comment by glyn** [comment]
Not really. I didn't realise this was just the default behaviour of CODEOWNERS. I therefore propose that we move everyone off the `*` line and add a comment (if possible) about why we did that, so others don't creep onto that line in future. Let me try that in a quick PR...

**Comment by glyn** [comment]
Here's a first stab at a solution: https://github.com/deislabs/duffle/pull/755
