### ISSUE TITLE
duffle bundle list not listing bundles

### ISSUE THREAD

**Issue by michelleN** [deislabs/duffle#754]
```
duffle [master]$ duffle bundle list
Error: cannot load bundle: invalid character '-' in numeric literal
```

**Comment by radu-matei** [comment]
Do you still have bundles that were PGP-signed?

**Comment by jeremyrickard** [comment]
I think this is only impacting things that were PGP-signed as @radu-matei mentioned. Going to close it since we've moved away from that.
