### ISSUE TITLE
Implement kubernetes driver

### ISSUE THREAD

**Issue by glyn** [deislabs/duffle#763]
A kubernetes driver would run the invocation image in kubernetes, probably as some kind of job with cluster admin privileges.

Note that the image would not have access to a docker daemon.

This should provide a workaround for the problem of needing to patch `~/.kube/config` for Docker Desktop. See https://github.com/deislabs/duffle/issues/762 for context.

**Comment by radu-matei** [comment]
We did start some efforts in #560 for Duffle, and https://github.com/deislabs/cnab-operator is an operator implementation that is very much in progress (and would really benefit from some contributions 😅)

**Comment by glyn** [comment]
Note to self: see also PR https://github.com/deislabs/duffle/pull/560 (currently gives 404 thanks to github).

**Comment by glyn** [comment]
Thanks @radu-matei! https://github.com/deislabs/duffle/pull/560 is currently givine me HTTP 500, but hopefully it will come back next week.

**Comment by radu-matei** [comment]
Try https://github.com/deislabs/duffle/pull/560/files, this seems to work for me.

**Comment by jlegrone** [comment]
I've been working on a k8s driver implementation that leverages the `Job` object (this gives us free retry and timeout logic). I wasn't aware of #560, but I think what I have is at feature parity. Can this issue be assigned to me for now?

**Comment by radu-matei** [comment]
@jlegrone - sure!
That being said, I'd like to further explore the choice to use a Job.
