### ISSUE TITLE
Suggestion: Load a credential from a directory

### ISSUE THREAD

**Issue by carolynvs** [deislabs/duffle#791]
I'm not sure if this is a bug, by design, or a gap but I can define a credential with a path that points to a directory but cannot then use that credential set. For example, I may have a couple files that I want to provide as credentials in a directory and instead of specifying each and every file, perhaps they don't have well-defined names, I want to point to the root configuration directory and give that to the bundle to mount. 

```
$ duffle credential show aws
name: aws
credentials:
- name: aws
  source:
    path: /tmp/aws
```

```
$ duffle install AWS -f .bundle.json --insecure -c aws
Error: credential "aws": read /tmp/aws: is a directory
```

I don't think there is a spec related reason for why this is true, so I'm hoping it's just a gap that we can fix?

**Comment by jeremyrickard** [comment]
I think this should be a valid way of operating, but I asked in the spec group for clarify on this:

```
If path is set, the value of the credential MUST be written into a file at the specified location on the invocation image's filesystem. This file name MUST NOT be present already on the invocation image's filesystem.
```

**Comment by jeremyrickard** [comment]
This was discussed in the cnab-go's 214 and the consensus was to make things explicit, so we'll close this.
