### ISSUE TITLE
duffle.json is not well documented

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#822]
The output bundle format (`bundle.json`) is well documented in the CNAB spec, but the Duffle build source format (`duffle.json`) doesn't seem to have anything similar.  Could we provide a link to it from the README or something?  (I would send a PR but I haven't been able to find the doc myself!)

(Specifically in this case I was trying to find out how to express parameters in `duffle.json`.)

**Comment by itowlson** [comment]
From the source code it looks like it's mostly the same as `bundle.json` except for the `invocationImages` section?

**Comment by glyn** [comment]
> From the source code it looks like it's mostly the same as `bundle.json` except for the `invocationImages` section?

That sounds right to me. Why not submit a PR along those lines?

**Comment by itowlson** [comment]
Yes - if that is correct then I will try to put together a docs PR.  Thanks!

**Comment by itowlson** [comment]
Mwahahahaha... I have tricked @squillace into volunteering to write some docs!  Freedom!

![image](https://user-images.githubusercontent.com/865538/62593985-f9abdb80-b92c-11e9-8bdf-f6bc26186e44.png)

**Comment by squillace** [comment]
Evil

**Comment by jeremyrickard** [comment]
@squillace @itowlson I think this is essentially a duplicate of #609. When this documentation is written can you please reference both issues in the PR?

**Comment by astrieanna** [comment]
If they're duplicates, would it make sense to close one of the issues now?

**Comment by jeremyrickard** [comment]
Closed as duplicate of #609
