### ISSUE TITLE
Absolutely baffling error message from `duffle export`

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#824]
Tried to export a full bundle (and got around the pull error by putting the invocation image under my Docker ID and logging into Docker Hub).  And instead got:

`Duffle export failed: Error preparing artifacts: MANIFEST_UNKNOWN: manifest unknown; map[Tag:e69ccbf72607bd1219972c438b322789f257a718]`

I don't even know what to report here.  The message is completely opaque to me.  Sorry.  If I can provide any more details then let me know.

**Comment by itowlson** [comment]
The error does not occur when exporting as manifest-only (with the `-t` option).

**Comment by itowlson** [comment]
The mysterious string is _not_ the hash in `~/.duffle/bundles`; I'm not sure what it is.

**Comment by glyn** [comment]
That kind of error occurs when `duffle export` is attempting to pull the images that the bundle refers to. However, I can't find the string `manifest unknown` in the relevant code. Are you sure the error message above is exactly that which occurred?

Anyway, the problem would appear to be with an image, so you coul try `docker pull` of the images in the bundle and see if that sheds any light.

**Comment by itowlson** [comment]
Oho!  I did the `docker pull` for the invocation image and here is what Docker told me:

```Error response from daemon: manifest for itowlson/arsebiscuits-cnab:e69ccbf72607bd1219972c438b322789f257a718 not found: manifest unknown: manifest unknown```

So there is the source of the mysterious message!

And if I do a `docker push`, _then_ the `docker pull` works (saying the image is up to date) and - tada - so does the `duffle export`.

So this is another symptom of the problem where Duffle tries to pull even when the image is available locally, and errors if the pull fails - but surfaced as a very cryptic error message.

Thanks for the catch @glyn!

**Comment by jeremyrickard** [comment]
@itowlson does this need to be a separate issue from #828 and the corresponding PR that @glyn has for it?

**Comment by itowlson** [comment]
Yes, I think @glyn's revised error message will address this.
