### ISSUE TITLE
Parameter not defined in bundle if parameter name does not match definition name

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#838]
I am finding that if I have parameters whose names do not match the names of their definitions then I get `Error: parameter <paramname> not defined in bundle`.

E.g. with

```
  "definitions": {
    "regionnn": {
      "type": "string",
      "default": "New Zealand South",
      "minLength": 4,
      "maxLength": 24
    }
  },
  "parameters": {
    "region": {
      "definition": "regionnn",
      "destination": {}
    },
  },
```

I run `duffle install ... --set region=nzsth` and get `Error: parameter region not defined in bundle`

**Comment by glyn** [comment]
Looks like a bug (and probably a missing test).

**Comment by jeremyrickard** [comment]
I think this is the same underlying issue as #816
