### ISSUE TITLE
"I say, I say, I say.  My bundle's got no outputs!" "How does it install?" "Terribly!"

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#839]
I have a bundle which does not declare any outputs.  When I `duffle install` it I get the following error message:

`Error: Install step failed: error copying outputs from container: Error: No such container:path: b10580a6de13c05edd959e1e15a6c273cee63b6056f7beb705cee347240dd2db:/cnab/app/outputs`

I don't know why it's looking for the `/cnab/app/outputs` directory.

Do I need to create a dummy directory in my invocation image?  This seems like a bit of a pain.

**Comment by jeremyrickard** [comment]
When you *HAVE* outputs, then you _must_ have that directory structure in the container.

But you do *NOT HAVE* outputs, so this seems like a bug.

**Comment by jeremyrickard** [comment]
This is stemming from an error in cnab-go. I'll create an issue there and reference this.

**Comment by jeremyrickard** [comment]
@itowlson hopefully this will get picked up in the next cnab-go release.
