### ISSUE TITLE
`duffle upgrade` fails against thick bundle

### ISSUE THREAD

**Issue by ashwin-venkatesh** [deislabs/duffle#845]
Hey!! We ran into an issue when trying to update the instance of our bundle. The command we ran for context is:
```
duffle upgrade ${CLUSTER_NAME} -c ./credentials.yaml \
    --set kubernetes_env="${CLUSTER_NAME}" \
    -m $PWD/relocated.json \
    --bundle-file build-service-*.tgz
```

This failed with the following error message: `Error: cannot load bundle: invalid character '\x1f' looking for beginning of value`.

We were able to work around this by importing the bundle and then running upgrade against the `bundle.json` directly. The duffle version we used was `duffle 0.2.0-beta.3`

**Comment by youreddy** [comment]
Ran into this issue as well!

**Comment by glyn** [comment]
I also noticed that `duffle upgrade` wasn't validating the bundle, so I'll fix that at the same time.
